package com.pwebapp.entity;
// Generated 13 Nov, 2015 10:02:23 PM by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Emp generated by hbm2java
 */
@Entity
@Table(name = "EMP")
public class Emp implements java.io.Serializable {

    /**
     *  @serial  -3825266510160616651L
     */
    private static final long serialVersionUID = -3825266510160616651L;
    
    private short empno;
    private Emp emp;
    private String ename;
    private String job;
    private Date hiredate;
    private BigDecimal sal;
    private BigDecimal comm;
    private Byte deptno;
    private Set<Emp> emps = new HashSet<>(0);

    public Emp() { // Default Constructor required
    }

    public Emp(short empno) {
        this.empno = empno;
    }

    public Emp(short empno, Emp emp, String ename, String job, Date hiredate, BigDecimal sal, BigDecimal comm,
            Byte deptno, Set<Emp> emps) {
        this.empno = empno;
        this.emp = emp;
        this.ename = ename;
        this.job = job;
        this.hiredate = hiredate;
        this.sal = sal;
        this.comm = comm;
        this.deptno = deptno;
        this.emps = emps;
    }

    @Id

    @Column(name = "EMPNO", unique = true, nullable = false, precision = 4, scale = 0)
    public short getEmpno() {
        return this.empno;
    }

    public void setEmpno(short empno) {
        this.empno = empno;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MGR")
    public Emp getEmp() {
        return this.emp;
    }

    public void setEmp(Emp emp) {
        this.emp = emp;
    }

    @Column(name = "ENAME", length = 10)
    public String getEname() {
        return this.ename;
    }

    public void setEname(String ename) {
        this.ename = ename;
    }

    @Column(name = "JOB", length = 9)
    public String getJob() {
        return this.job;
    }

    public void setJob(String job) {
        this.job = job;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "HIREDATE", length = 7)
    public Date getHiredate() {
        return this.hiredate;
    }

    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }

    @Column(name = "SAL", precision = 7)
    public BigDecimal getSal() {
        return this.sal;
    }

    public void setSal(BigDecimal sal) {
        this.sal = sal;
    }

    @Column(name = "COMM", precision = 7)
    public BigDecimal getComm() {
        return this.comm;
    }

    public void setComm(BigDecimal comm) {
        this.comm = comm;
    }

    @Column(name = "DEPTNO", precision = 2, scale = 0)
    public Byte getDeptno() {
        return this.deptno;
    }

    public void setDeptno(Byte deptno) {
        this.deptno = deptno;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "emp")
    public Set<Emp> getEmps() {
        return this.emps;
    }

    public void setEmps(Set<Emp> emps) {
        this.emps = emps;
    }

}
